CREATE TABLE putrequests (
	id VARCHAR PRIMARY KEY
);
CREATE TABLE recipients (
	id SERIAL PRIMARY KEY,
	phone_number VARCHAR UNIQUE NOT NULL,
	user_id VARCHAR UNIQUE NOT NULL,
	room_id VARCHAR UNIQUE NOT NULL
);

